# Generated by Django 4.2.7 on 2024-02-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_election',
            name='election_fordate',
            field=models.DateField(),
        ),
    ]
