# Generated by Django 5.0.2 on 2024-02-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_alter_tbl_election_election_fordate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_election',
            name='election_status',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
