# Generated by Django 4.2.7 on 2024-02-18 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=50)),
                ('teacher_address', models.CharField(max_length=500)),
                ('teacher_email', models.EmailField(max_length=30, unique=True)),
                ('teacher_contact', models.CharField(max_length=20)),
                ('teacher_photo', models.FileField(upload_to='TeacherPhoto/')),
                ('teacher_password', models.CharField(max_length=10, unique=True)),
                ('teacher_college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_newcollege')),
                ('teacher_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_course')),
            ],
        ),
    ]
