# Generated by Django 4.2.7 on 2024-02-18 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
        ('College', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_teacher',
            name='election',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_election'),
        ),
    ]
