# Generated by Django 4.2.7 on 2024-02-19 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0001_initial'),
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_classcandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_gender', models.CharField(max_length=1)),
                ('candidate_status', models.IntegerField(default=0)),
                ('candidate_election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_election')),
                ('candidate_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_newstudent')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_content', models.CharField(max_length=100)),
                ('feedback_date', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_newstudent')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_title', models.CharField(max_length=100)),
                ('complaint_content', models.TextField()),
                ('complaint_reply', models.TextField(default='Not Yet Viewed')),
                ('complaint_date', models.DateField(auto_now_add=True)),
                ('complaint_status', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_newstudent')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_classpolling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polling_datetime', models.DateField(auto_now_add=True)),
                ('polling_status', models.IntegerField(default=0)),
                ('polling_classcandidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.tbl_classcandidate')),
                ('polling_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_newstudent')),
            ],
        ),
    ]
