# Generated by Django 5.0.2 on 2024-02-22 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_alter_tbl_election_election_fordate'),
        ('Guest', '0001_initial'),
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_collegecandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_status', models.IntegerField(default=0)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_election')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_position')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_newstudent')),
            ],
        ),
    ]
