# Generated by Django 5.0.2 on 2024-02-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_tbl_semmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_semmark',
            name='sem1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tbl_semmark',
            name='sem2',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tbl_semmark',
            name='sem3',
            field=models.CharField(max_length=20),
        ),
    ]
