# Generated by Django 5.0.2 on 2024-02-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_alter_tbl_semmark_sem1_alter_tbl_semmark_sem2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_semmark',
            name='sem1',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='tbl_semmark',
            name='sem2',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='tbl_semmark',
            name='sem3',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
