# Generated by Django 5.0.2 on 2024-02-23 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_alter_tbl_semmark_sem1_alter_tbl_semmark_sem2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_collegepolling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polling_datetime', models.DateField(auto_now_add=True)),
                ('polling_status', models.IntegerField(default=0)),
                ('arts_candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arts', to='Student.tbl_classcandidate')),
                ('chairperson_candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chairperson', to='Student.tbl_classcandidate')),
                ('editor_candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editor', to='Student.tbl_classcandidate')),
                ('first_candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first', to='Student.tbl_classcandidate')),
                ('general_candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general', to='Student.tbl_classcandidate')),
                ('lady_candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lady', to='Student.tbl_classcandidate')),
                ('polling_student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='Student.tbl_classcandidate')),
                ('sec_candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sec', to='Student.tbl_classcandidate')),
                ('third_candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third', to='Student.tbl_classcandidate')),
                ('union_candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='union', to='Student.tbl_classcandidate')),
                ('vchairperson_candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vchairperson', to='Student.tbl_classcandidate')),
            ],
        ),
    ]
