# Generated by Django 5.0.2 on 2024-02-24 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_tbl_collegepolling'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_collegepolling',
        ),
    ]
