# Generated by Django 4.2.7 on 2024-02-18 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_newcollege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=50)),
                ('college_address', models.CharField(max_length=100)),
                ('college_email', models.EmailField(max_length=254, unique='true')),
                ('college_contact', models.CharField(max_length=50)),
                ('college_logo', models.FileField(upload_to='CollegeLogo/')),
                ('college_proof', models.FileField(upload_to='CollegeProof/')),
                ('college_password', models.CharField(max_length=50, unique='true')),
                ('college_status', models.CharField(default=0, max_length=20)),
                ('college_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_newstudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('student_address', models.CharField(max_length=100)),
                ('student_email', models.EmailField(max_length=254, unique='true')),
                ('student_contact', models.CharField(max_length=50)),
                ('student_adno', models.CharField(max_length=50)),
                ('student_photo', models.FileField(upload_to='StudentPhoto/')),
                ('student_proof', models.FileField(upload_to='StudentProof/')),
                ('student_password', models.CharField(max_length=50, unique='true')),
                ('student_ststus', models.CharField(default=0, max_length=20)),
                ('student_college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_newcollege')),
                ('student_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_course')),
                ('student_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_year')),
            ],
        ),
    ]
